"""Reproducible 10-question baseline/final retrieval and RAGAS evaluation."""

from __future__ import annotations

import argparse
import asyncio
import json
import math
import os
import re
import time
from dataclasses import dataclass
from pathlib import Path
from statistics import mean
from typing import Any, Sequence

from dotenv import load_dotenv

from agent import GovernanceAgent
from reasoning import SYNTHESIS_SYSTEM_PROMPT, assemble_context
from retrieval import Document, HybridRetriever, SearchResult, load_documents


@dataclass(frozen=True)
class EvaluationCase:
    question: str
    reference: str
    relevant_ids: tuple[str, ...]


CASES = (
    EvaluationCase(
        "Is an AI tool that filters CVs for recruitment high-risk under the EU AI Act?",
        "Yes. Annex III lists systems used to analyse and filter job applications or evaluate candidates as high-risk, subject to Article 6.",
        ("eu_ai_act_high_risk_classification",),
    ),
    EvaluationCase(
        "What must a provider do to manage risks in a high-risk AI system?",
        "Article 9 requires a documented continuous lifecycle process to identify, evaluate, mitigate, test, and review risks, including foreseeable misuse.",
        ("eu_ai_act_high_risk_provider_duties",),
    ),
    EvaluationCase(
        "Must customers be told that a support chatbot is AI?",
        "Article 50 generally requires people interacting directly with AI to be informed unless the interaction is obvious in context.",
        ("eu_ai_act_transparency",),
    ),
    EvaluationCase(
        "Can an employer use AI emotion recognition on workers?",
        "Article 5 generally prohibits emotion inference in workplaces, except systems intended for medical or safety reasons.",
        ("eu_ai_act_prohibited_practices",),
    ),
    EvaluationCase(
        "What human oversight capabilities are required for a high-risk system?",
        "Article 14 requires effective oversight enabling competent people to understand limitations, detect anomalies, avoid automation bias, interpret and override output, and intervene or stop operation.",
        ("eu_ai_act_high_risk_provider_duties",),
    ),
    EvaluationCase(
        "How long must a deployer retain logs generated by a high-risk AI system?",
        "Article 26 requires logs under the deployer's control to be retained for an appropriate period of at least six months unless other applicable law provides otherwise.",
        ("eu_ai_act_deployer_duties",),
    ),
    EvaluationCase(
        "What documentation does a general-purpose AI model provider need?",
        "Article 53 requires model technical documentation, downstream information, a copyright compliance policy, and a public training-content summary.",
        ("eu_ai_act_gpai",),
    ),
    EvaluationCase(
        "When does the EU AI Act generally apply, and when did prohibited-practice rules apply?",
        "The Act generally applies from 2 August 2026; Chapters I and II, including prohibited practices, applied from 2 February 2025.",
        ("eu_ai_act_application_dates",),
    ),
    EvaluationCase(
        "When does GDPR restrict a solely automated decision about a person?",
        "GDPR Article 22 covers solely automated decisions, including profiling, that produce legal or similarly significant effects, subject to limited exceptions and safeguards.",
        ("gdpr_automated_decisions",),
    ),
    EvaluationCase(
        "What data governance is required for training a high-risk AI system?",
        "Article 10 requires intended-purpose-appropriate governance for training, validation, and testing data, including relevance, representativeness, quality, bias examination, and mitigation.",
        ("eu_ai_act_high_risk_provider_duties",),
    ),
)

TOKEN_PATTERN = re.compile(r"\b[\w'-]+\b", re.UNICODE)


def _tokens(text: str) -> list[str]:
    return TOKEN_PATTERN.findall(text.lower())


def baseline_search(documents: Sequence[Document], query: str, top_k: int = 5) -> list[SearchResult]:
    """Basic full-document bag-of-words cosine baseline."""
    query_counts = {token: _tokens(query).count(token) for token in set(_tokens(query))}
    query_norm = math.sqrt(sum(value * value for value in query_counts.values())) or 1.0
    ranked: list[tuple[float, Document]] = []
    for document in documents:
        document_tokens = _tokens(document.text)
        document_counts = {
            token: document_tokens.count(token) for token in set(document_tokens)
        }
        document_norm = math.sqrt(
            sum(value * value for value in document_counts.values())
        ) or 1.0
        dot_product = sum(
            value * document_counts.get(token, 0)
            for token, value in query_counts.items()
        )
        ranked.append((dot_product / (query_norm * document_norm), document))
    return [
        SearchResult(document=document, score=score, matched_chunk=document.text)
        for score, document in sorted(ranked, key=lambda item: item[0], reverse=True)[:top_k]
    ]


def retrieval_proxy(
    cases: Sequence[EvaluationCase],
    result_sets: Sequence[Sequence[SearchResult]],
) -> dict[str, float]:
    """Compute deterministic ID-based retrieval metrics, separate from RAGAS."""
    recalls: list[float] = []
    average_precisions: list[float] = []
    for case, results in zip(cases, result_sets):
        retrieved = [result.document.id for result in results]
        relevant = set(case.relevant_ids)
        hits = len(relevant.intersection(retrieved))
        recalls.append(hits / len(relevant))
        relevant_seen = 0
        precision_sum = 0.0
        for rank, document_id in enumerate(retrieved, start=1):
            if document_id in relevant:
                relevant_seen += 1
                precision_sum += relevant_seen / rank
        average_precisions.append(precision_sum / len(relevant))
    return {
        "id_context_recall": mean(recalls),
        "id_average_precision": mean(average_precisions),
    }


def _contexts(results: Sequence[SearchResult]) -> list[str]:
    return [result.document.text for result in results]


def _final_results(retriever: HybridRetriever, question: str) -> list[SearchResult]:
    primary = retriever.search(question, top_k=5)
    risk = retriever.search(
        f"EU AI Act prohibited high-risk transparency obligations {question}",
        top_k=3,
    )
    return list({result.document.id: result for result in primary + risk}.values())


def _baseline_answer(client: Any, model: str, case: EvaluationCase, results: list[SearchResult]) -> str:
    response = client.responses.create(
        model=model,
        instructions=SYNTHESIS_SYSTEM_PROMPT,
        input=f"Question:\n{case.question}\n\nEvidence:\n{assemble_context(results)}",
        max_output_tokens=700,
    )
    return response.output_text


async def _ragas_scores(
    rows: Sequence[dict[str, Any]],
    model: str,
) -> dict[str, float]:
    from openai import AsyncOpenAI
    from ragas.embeddings.base import embedding_factory
    from ragas.llms import llm_factory
    from ragas.metrics.collections import (
        AnswerRelevancy,
        ContextPrecisionWithReference,
        ContextRecall,
        Faithfulness,
    )

    client = AsyncOpenAI()
    llm = llm_factory(model, client=client, max_tokens=4096)
    embeddings = embedding_factory(
        "openai",
        model="text-embedding-3-small",
        client=client,
    )
    metrics = {
        "context_recall": ContextRecall(llm=llm),
        "context_precision": ContextPrecisionWithReference(llm=llm),
        "faithfulness": Faithfulness(llm=llm),
        "answer_relevancy": AnswerRelevancy(llm=llm, embeddings=embeddings),
    }
    scores: dict[str, list[float]] = {name: [] for name in metrics}
    for index, row in enumerate(rows, start=1):
        print(f"RAGAS scoring question {index}/{len(rows)}", flush=True)
        scores["context_recall"].append(
            (
                await metrics["context_recall"].ascore(
                    user_input=row["question"],
                    retrieved_contexts=row["contexts"],
                    reference=row["reference"],
                )
            ).value
        )
        scores["context_precision"].append(
            (
                await metrics["context_precision"].ascore(
                    user_input=row["question"],
                    reference=row["reference"],
                    retrieved_contexts=row["contexts"],
                )
            ).value
        )
        scores["faithfulness"].append(
            (
                await metrics["faithfulness"].ascore(
                    user_input=row["question"],
                    response=row["answer"],
                    retrieved_contexts=row["contexts"],
                )
            ).value
        )
        scores["answer_relevancy"].append(
            (
                await metrics["answer_relevancy"].ascore(
                    user_input=row["question"],
                    response=row["answer"],
                )
            ).value
        )
    return {name: mean(values) for name, values in scores.items()}


def run(retrieval_only: bool = False) -> dict[str, Any]:
    project_root = Path(__file__).resolve().parents[1]
    load_dotenv(project_root / ".env")
    documents = load_documents(project_root / "data")
    retriever = HybridRetriever(documents)
    baseline_results = [baseline_search(documents, case.question) for case in CASES]
    final_results = [_final_results(retriever, case.question) for case in CASES]
    output: dict[str, Any] = {
        "question_count": len(CASES),
        "retrieval_proxy": {
            "baseline": retrieval_proxy(CASES, baseline_results),
            "final": retrieval_proxy(CASES, final_results),
        },
    }
    if retrieval_only:
        return output
    if not os.getenv("OPENAI_API_KEY"):
        raise RuntimeError(
            "OPENAI_API_KEY is required for genuine RAGAS and operational measurements. "
            "Add it to .env or run with --retrieval-only."
        )

    from openai import OpenAI

    model = os.getenv("OPENAI_MODEL", "gpt-4.1-mini")
    client = OpenAI()
    agent = GovernanceAgent()
    checkpoint_path = project_root / ".evaluation_checkpoint.json"
    if checkpoint_path.exists():
        checkpoint = json.loads(checkpoint_path.read_text(encoding="utf-8"))
        baseline_rows = checkpoint["baseline_rows"]
        final_rows = checkpoint["final_rows"]
        latencies = checkpoint["latencies"]
        costs = checkpoint["costs"]
        tool_counts = checkpoint["tool_counts"]
        print("Reusing checkpointed model outputs.", flush=True)
    else:
        baseline_rows: list[dict[str, Any]] = []
        final_rows: list[dict[str, Any]] = []
        latencies: list[float] = []
        costs: list[float] = []
        for index, (case, baseline, final) in enumerate(
            zip(CASES, baseline_results, final_results),
            start=1,
        ):
            print(f"Generating answers {index}/{len(CASES)}", flush=True)
            baseline_answer = _baseline_answer(client, model, case, baseline)
            before_cost = agent.estimated_cost_usd
            started = time.perf_counter()
            final_answer = agent.run(case.question).answer
            latencies.append(time.perf_counter() - started)
            costs.append(agent.estimated_cost_usd - before_cost)
            baseline_rows.append(
                {
                    "question": case.question,
                    "reference": case.reference,
                    "contexts": _contexts(baseline),
                    "answer": baseline_answer,
                }
            )
            final_rows.append(
                {
                    "question": case.question,
                    "reference": case.reference,
                    "contexts": _contexts(final),
                    "answer": final_answer,
                }
            )
        tool_counts = agent.tool_counts
        checkpoint_path.write_text(
            json.dumps(
                {
                    "baseline_rows": baseline_rows,
                    "final_rows": final_rows,
                    "latencies": latencies,
                    "costs": costs,
                    "tool_counts": tool_counts,
                },
                indent=2,
                ensure_ascii=False,
            )
            + "\n",
            encoding="utf-8",
        )

    output["ragas"] = {
        "baseline": asyncio.run(_ragas_scores(baseline_rows, model)),
        "final": asyncio.run(_ragas_scores(final_rows, model)),
    }
    output["operations"] = {
        "average_latency_seconds": mean(latencies),
        "average_cost_usd": mean(costs),
        "tool_call_distribution": tool_counts,
        "pricing_usd_per_1m_tokens": {
            "input": float(os.getenv("OPENAI_INPUT_COST_PER_1M", "0.40")),
            "output": float(os.getenv("OPENAI_OUTPUT_COST_PER_1M", "1.60")),
        },
    }
    return output


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--retrieval-only", action="store_true")
    parser.add_argument(
        "--output",
        default="evaluation_results.json",
        help="Path for machine-readable results.",
    )
    args = parser.parse_args()
    try:
        result = run(retrieval_only=args.retrieval_only)
    except RuntimeError as error:
        print(error)
        return 2
    Path(args.output).write_text(
        json.dumps(result, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(json.dumps(result, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
